language: generic

# use a Mac OSX image
os: osx

# run the script to download and install Unity editor
install:
- sudo -E sh ./Scripts/install.sh

# run the script for unit tests and builds
script:
- sudo -E sh ./Scripts/build.sh

branches:
  only: Unity-travis-yml

# environment variables used in bash scripts
env:
  global:
  - UNITYCI_PROJECT_NAME="LeagueOfTowers"